import type { EventChoice, EventDefinition, EventType, RiskLevel } from "./types.ts";

interface CareerStorySpec {
  id: string;
  pack: "growth" | "shock" | "transition" | "independent";
  stage: number;
  type: EventType;
  title: string;
  narrative: string;
  triggerTags: string[];
  requiredAnyTags?: string[];
  prepare: [string, string];
  negotiate: [string, string];
  bold: [string, string];
}

const SPECS: CareerStorySpec[] = [
  {
    id: "career-growth-review",
    pack: "growth",
    stage: 1,
    type: "职业",
    title: "绩效会议要求你证明自己的价值",
    narrative: "主管不再接受“我很努力”的陈述，要求你用结果、反馈和可替代性说明下一年的位置。",
    triggerTags: ["学习", "职业", "人力资本", "稳定交付"],
    prepare: ["整理成果证据", "把交付、影响与同事反馈整理成一页证据，而不是临场争辩。"],
    negotiate: ["提前校准评价标准", "先确认岗位标准与预算边界，再讨论职级和收入。"],
    bold: ["直接要求跳级晋升", "用外部机会和关键项目作为筹码，要求一次明显跃迁。"],
  },
  {
    id: "career-growth-stretch",
    pack: "growth",
    stage: 2,
    type: "职业",
    title: "一个跨部门难题落到你桌上",
    narrative: "任务能带来可见度，却没有额外人手。承担它可能形成晋升证据，也可能透支健康和关系。",
    triggerTags: ["管理", "项目", "信用"],
    requiredAnyTags: ["职业包:growth:1"],
    prepare: ["缩小范围后承接", "先定义交付边界、资源与失败条件，只承诺可以验证的部分。"],
    negotiate: ["用资源交换责任", "要求明确人手、权限和复盘标准，再接受项目负责人角色。"],
    bold: ["全盘接下高曝光任务", "接受高压力与模糊边界，争取在短期内成为不可替代的人。"],
  },
  {
    id: "career-growth-pay-window",
    pack: "growth",
    stage: 3,
    type: "职业",
    title: "薪酬窗口打开，但预算并不透明",
    narrative: "你已经承担了更多责任。公司愿意谈，但希望用未来承诺替代当期薪酬。",
    triggerTags: ["谈判", "职业", "信用"],
    requiredAnyTags: ["职业包:growth:2"],
    prepare: ["争取分阶段兑现", "把现金、职级、培训和复盘日期写进分阶段承诺。"],
    negotiate: ["拿市场证据重谈", "用同岗薪酬与真实成果提出可验证的调整区间。"],
    bold: ["用离职选项施压", "明确表示没有实质调整就会离开，但准备承担关系与失业风险。"],
  },
  {
    id: "career-growth-vacancy",
    pack: "growth",
    stage: 4,
    type: "职业",
    title: "管理岗位突然空缺",
    narrative: "团队需要临时负责人。新位置带来收入和影响力，也会把人员冲突、预算和结果责任一起交给你。",
    triggerTags: ["管理", "领导力", "关系"],
    requiredAnyTags: ["职业包:growth:3"],
    prepare: ["先做代理负责人", "用九十天代理期验证管理适配，并保留回到专业路线的出口。"],
    negotiate: ["组建支持联盟", "先获得关键同事和上级支持，再共同承担过渡期目标。"],
    bold: ["立即竞争正式岗位", "承担完整责任并要求正式头衔、预算和薪酬。"],
  },
  {
    id: "career-growth-identity",
    pack: "growth",
    stage: 5,
    type: "职业",
    title: "专业深耕还是管理扩张",
    narrative: "成长路线走到第一次身份分岔。继续向上并不等于继续做擅长的事，你必须选择未来愿意承担的责任。",
    triggerTags: ["职业", "管理", "专业"],
    requiredAnyTags: ["职业包:growth:4"],
    prepare: ["保留专业主线", "选择专家路线，用作品、研究和稀缺能力换取更高议价权。"],
    negotiate: ["建立双轨角色", "同时承担有限管理责任与核心专业交付，定期复核边界。"],
    bold: ["转向完整管理路线", "放下部分专业确定性，承担团队、预算和组织结果。"],
  },
  {
    id: "career-shock-freeze",
    pack: "shock",
    stage: 1,
    type: "行业",
    title: "预算冻结从传闻变成邮件",
    narrative: "行业放缓传到公司内部：招聘暂停、项目缩减。风险尚未落到个人，但准备窗口已经出现。",
    triggerTags: ["放缓", "衰退", "主业", "现金流"],
    prepare: ["先补现金缓冲", "暂停非必要承诺，把未来六个月的选择权留在手中。"],
    negotiate: ["主动确认岗位风险", "向主管询问业务优先级、团队位置和可迁移任务。"],
    bold: ["提前寻找外部机会", "在消息公开前进入市场，承担分心与关系成本。"],
  },
  {
    id: "career-shock-reorg",
    pack: "shock",
    stage: 2,
    type: "职业",
    title: "组织重组取消了熟悉的边界",
    narrative: "你的团队被并入新部门。岗位名称还在，但评价者、目标和资源都发生了变化。",
    triggerTags: ["职业韧性", "关系", "技能"],
    requiredAnyTags: ["职业包:shock:1"],
    prepare: ["建立新角色地图", "识别新决策者、关键交付与可以迁移的能力证据。"],
    negotiate: ["与新主管重谈目标", "把旧承诺和新优先级写清楚，避免承担双份责任。"],
    bold: ["争取重组中的新岗位", "利用结构变化主动竞争更高位置，也承担政治与失败风险。"],
  },
  {
    id: "career-shock-notice",
    pack: "shock",
    stage: 3,
    type: "职业",
    title: "你的岗位进入裁撤名单",
    narrative: "风险不再抽象。公司给出短暂窗口，你必须在情绪、法律权利、现金流与下一步之间做决定。",
    triggerTags: ["职业韧性", "合同", "应急金"],
    requiredAnyTags: ["职业包:shock:2"],
    prepare: ["核对补偿与权益", "保留文件、确认社保与奖金口径，用规则守住底线。"],
    negotiate: ["争取内部转岗窗口", "用交付证据和关系信用交换一次内部面试。"],
    bold: ["立即离开并全力转型", "放弃部分确定性，把时间投入新职业或独立项目。"],
  },
  {
    id: "career-shock-runway",
    pack: "shock",
    stage: 4,
    type: "风险",
    title: "失去工资后的第一个现金流月",
    narrative: "补偿款到账后，住房、负债和家庭支出仍按时发生。真正的风险来自资金期限与恢复速度。",
    triggerTags: ["现金流", "负债管理", "家庭"],
    requiredAnyTags: ["职业包:shock:3"],
    prepare: ["重做生存预算", "区分必须支出、可暂停承诺和转型投入，先延长跑道。"],
    negotiate: ["调用可信关系", "提出具体能力与可交付事项，争取项目、介绍或过渡工作。"],
    bold: ["集中押注一次转型", "用大部分缓冲完成训练和作品，争取更快进入新行业。"],
  },
  {
    id: "career-shock-comeback",
    pack: "shock",
    stage: 5,
    type: "机会",
    title: "恢复期出现三种不同的入口",
    narrative: "旧行业回暖、新行业愿意给试用机会，一位合作伙伴也提出项目制工作。你要决定恢复什么，而不是只恢复工资。",
    triggerTags: ["成功转型", "低成本试错", "关系复利"],
    requiredAnyTags: ["职业包:shock:4"],
    prepare: ["先选择稳定回归", "用确定现金流恢复底盘，再继续积累新方向证据。"],
    negotiate: ["接受项目制组合", "用多个真实项目替代单一岗位，并控制客户集中度。"],
    bold: ["进入全新职业身份", "接受学习曲线和短期收入波动，彻底更换长期路线。"],
  },
  {
    id: "career-transition-gap",
    pack: "transition",
    stage: 1,
    type: "职业",
    title: "目标职业暴露出真实技能缺口",
    narrative: "招聘描述看起来熟悉，但真实作品、工具熟练度与行业经验之间仍有明显距离。",
    triggerTags: ["学习", "转型受挫", "时代适配", "人力资本"],
    prepare: ["拆成最小学习闭环", "只补足能完成第一个真实作品的能力，不追求证书堆叠。"],
    negotiate: ["寻找带教型项目", "用低风险交付交换反馈、案例和行业关系。"],
    bold: ["参加高强度训练", "投入更多现金与时间，争取在一个周期内完成能力跃迁。"],
  },
  {
    id: "career-transition-portfolio",
    pack: "transition",
    stage: 2,
    type: "机会",
    title: "一家公司愿意看作品，不先看头衔",
    narrative: "机会窗口很短。你需要决定展示未经验证的想法，还是投入时间形成可运行的样本。",
    triggerTags: ["项目", "作品", "交付"],
    requiredAnyTags: ["职业包:transition:1"],
    prepare: ["完成一个可运行样本", "用小而完整的作品证明问题理解、取舍和交付能力。"],
    negotiate: ["联合真实用户共创", "让使用者反馈成为作品证据，而不是只展示视觉包装。"],
    bold: ["一次制作完整作品集", "投入大量时间形成系列案例，承担错过当前窗口的风险。"],
  },
  {
    id: "career-transition-recruiter",
    pack: "transition",
    stage: 3,
    type: "职业",
    title: "招聘者提出一场非正式谈话",
    narrative: "这不是录用承诺，而是一次判断行业需求、薪酬区间和能力缺口的高价值信息机会。",
    triggerTags: ["职业", "关系", "谈判"],
    requiredAnyTags: ["职业包:transition:2"],
    prepare: ["把谈话当作尽调", "询问真实任务、团队能力和失败标准，不急着推销自己。"],
    negotiate: ["展示证据并询问差距", "用作品换取具体反馈与下一轮准备方向。"],
    bold: ["直接争取正式面试", "主动要求进入流程，接受准备不足被快速淘汰的可能。"],
  },
  {
    id: "career-transition-trial",
    pack: "transition",
    stage: 4,
    type: "职业",
    title: "一份降薪试用邀请摆在面前",
    narrative: "新路线提供成长与迁移价值，但短期收入下降，家庭与现金缓冲会共同决定你是否承担得起。",
    triggerTags: ["机会成本", "现金流", "职业"],
    requiredAnyTags: ["职业包:transition:3"],
    prepare: ["保留旧收入并兼职试用", "降低转换速度，用时间冲突换取更低现金风险。"],
    negotiate: ["争取阶段薪酬条款", "把试用目标、转正时间和薪酬恢复条件写清楚。"],
    bold: ["全职进入新赛道", "接受短期降薪，把全部精力投入能力与行业关系积累。"],
  },
  {
    id: "career-transition-choice",
    pack: "transition",
    stage: 5,
    type: "职业",
    title: "旧身份与新能力同时向你索取时间",
    narrative: "转型不再是想象，而是资源冲突。你必须决定哪条路线成为主线，哪条只保留为选择权。",
    triggerTags: ["职业", "技能组合", "机会成本"],
    requiredAnyTags: ["职业包:transition:4"],
    prepare: ["让新路线成为副线", "保留旧职业现金流，用更长时间积累新路线证据。"],
    negotiate: ["设计半年过渡期", "设定收入、作品与健康指标，到期用证据决定主线。"],
    bold: ["正式更换职业身份", "结束旧路线，把资源集中到新职业的成长与网络。"],
  },
  {
    id: "career-independent-referral",
    pack: "independent",
    stage: 1,
    type: "机会",
    title: "熟人介绍来第一位潜在客户",
    narrative: "客户的问题真实，但需求模糊、预算有限。第一单会定义你的定价、边界与口碑。",
    triggerTags: ["副业尝试", "自由机会", "关系复利", "客户"],
    prepare: ["先做付费诊断", "用小额固定范围识别问题，再决定是否承接完整项目。"],
    negotiate: ["共同定义交付范围", "把成果、时间、修改次数和付款节点写清楚。"],
    bold: ["低价拿下完整项目", "用更大投入换案例与转介绍，承担范围失控风险。"],
  },
  {
    id: "career-independent-contract",
    pack: "independent",
    stage: 2,
    type: "关系",
    title: "口头承诺需要变成第一份合同",
    narrative: "关系可以打开门，却不能替代交付、验收、知识产权和退出机制。",
    triggerTags: ["合同", "信用", "客户"],
    requiredAnyTags: ["职业包:independent:1"],
    prepare: ["使用标准小合同", "明确范围、时间、验收和分期付款，保持低交易成本。"],
    negotiate: ["按里程碑共同签署", "让双方在每个阶段重新确认承诺与变化。"],
    bold: ["接受模糊合作换速度", "先开工再补文件，承担回款和关系争议风险。"],
  },
  {
    id: "career-independent-scope",
    pack: "independent",
    stage: 3,
    type: "职业",
    title: "客户不断增加“顺手”的额外需求",
    narrative: "项目收入没有变，时间和责任却持续扩大。拒绝可能伤害关系，接受则会吞噬利润与主业精力。",
    triggerTags: ["交付", "机会成本", "谈判"],
    requiredAnyTags: ["职业包:independent:2"],
    prepare: ["按原范围交付", "记录新增需求并放入下一阶段，不让口头变化穿透边界。"],
    negotiate: ["提交变更报价", "把新增价值、时间和费用透明化，让客户重新选择。"],
    bold: ["全部接受以争取口碑", "牺牲利润和精力，赌客户会带来更大后续机会。"],
  },
  {
    id: "career-independent-payment",
    pack: "independent",
    stage: 4,
    type: "风险",
    title: "验收完成后，尾款开始延迟",
    narrative: "账面收入与现金流第一次发生分离。关系、合同证据和客户集中度决定你能否承受拖延。",
    triggerTags: ["现金流", "合同", "客户"],
    requiredAnyTags: ["职业包:independent:3"],
    prepare: ["按合同暂停后续服务", "保留证据并停止新增投入，优先守住现金和边界。"],
    negotiate: ["重订分期回款计划", "用明确日期与阶段金额交换客户的短期周转空间。"],
    bold: ["继续投入等待大单", "维持服务以争取长期合同，承担更高应收账款风险。"],
  },
  {
    id: "career-independent-scale",
    pack: "independent",
    stage: 5,
    type: "职业",
    title: "独立项目要不要变成一门事业",
    narrative: "你已经拥有客户、案例和现金流样本。扩大规模会引入团队、固定成本、治理与新的失败方式。",
    triggerTags: ["经营", "收入多元", "管理"],
    requiredAnyTags: ["职业包:independent:4"],
    prepare: ["保持个人工作室", "限制项目数量，优先维持利润、健康和交付质量。"],
    negotiate: ["与伙伴建立小型团队", "先明确股权、职责、客户归属和退出机制。"],
    bold: ["招聘并扩大经营", "承担固定成本与管理责任，争取从个人收入升级为企业价值。"],
  },
];

function makeChoice(
  eventId: string,
  pack: CareerStorySpec["pack"],
  stage: number,
  strategy: "prepare" | "negotiate" | "bold",
  copy: [string, string],
): EventChoice {
  const profile: Record<
    typeof strategy,
    {
      risk: RiskLevel;
      cost: number;
      timeCost: number;
      baseProbability: number;
      effects: EventChoice["effects"];
      successEffects: EventChoice["successEffects"];
      failureEffects: EventChoice["failureEffects"];
      knowledge: string[];
    }
  > = {
    prepare: {
      risk: "低",
      cost: 1_200,
      timeCost: 1,
      baseProbability: 0.82,
      effects: { cash: -1_200, energy: -2 },
      successEffects: { credit: 2, stress: -2 },
      failureEffects: { stress: 1 },
      knowledge: ["低成本试错", "职业韧性"],
    },
    negotiate: {
      risk: "中",
      cost: 2_500,
      timeCost: 2,
      baseProbability: 0.64,
      effects: { cash: -2_500, energy: -4 },
      successEffects: { monthlyIncome: 420, relationship: 3, credit: 2 },
      failureEffects: { relationship: -1, stress: 3 },
      knowledge: ["谈判", "关系复利", "合同"],
    },
    bold: {
      risk: "高",
      cost: 6_000,
      timeCost: 3,
      baseProbability: 0.43,
      effects: { cash: -6_000, energy: -7, stress: 3 },
      successEffects: { cash: 12_000, monthlyIncome: 900, happiness: 4 },
      failureEffects: { cash: -3_000, stress: 6, happiness: -3 },
      knowledge: ["机会成本", "风险承受力", "人力资本"],
    },
  };
  const selected = profile[strategy];
  return {
    id: `${eventId}-${strategy}`,
    label: copy[0],
    description: copy[1],
    cost: selected.cost,
    timeCost: selected.timeCost,
    risk: selected.risk,
    baseProbability: selected.baseProbability,
    effects: selected.effects,
    successEffects: selected.successEffects,
    failureEffects: selected.failureEffects,
    knowledgeTags: selected.knowledge,
    memoryTags: [
      `职业包:${pack}:${stage}`,
      `职业包:事件:${eventId}`,
      `职业策略:${strategy}`,
    ],
  };
}

export const CAREER_STORY_EVENTS: EventDefinition[] = SPECS.map((spec) => ({
  id: spec.id,
  type: spec.type,
  title: spec.title,
  narrative: spec.narrative,
  minTurn: spec.stage,
  requiredAnyTags: spec.requiredAnyTags,
  blockedTags: [`职业包:事件:${spec.id}`],
  triggerTags: spec.triggerTags,
  storyPackId: `career-${spec.pack}`,
  storyStage: spec.stage,
  weight: spec.stage === 1 ? 1.25 : 1.8,
  choices: [
    makeChoice(spec.id, spec.pack, spec.stage, "prepare", spec.prepare),
    makeChoice(spec.id, spec.pack, spec.stage, "negotiate", spec.negotiate),
    makeChoice(spec.id, spec.pack, spec.stage, "bold", spec.bold),
  ],
}));
