import type { EventChoice, EventDefinition, EventType, NumericEffects, RiskLevel } from "./types.ts";

type LifeStoryPack = "business" | "family" | "investment" | "contract" | "consumer" | "platform";
type Strategy = "guarded" | "collaborative" | "bold";

interface LifeStorySpec {
  id: string;
  pack: LifeStoryPack;
  stage: number;
  type: EventType;
  title: string;
  narrative: string;
  triggerTags: string[];
  requiredAnyTags?: string[];
  guarded: [string, string];
  collaborative: [string, string];
  bold: [string, string];
}

interface StrategyProfile {
  risk: RiskLevel;
  cost: number;
  timeCost: number;
  baseProbability: number;
  effects: NumericEffects;
  successEffects: NumericEffects;
  failureEffects: NumericEffects;
  knowledge: string[];
}

const SPECS: LifeStorySpec[] = [
  {
    id: "business-order",
    pack: "business",
    stage: 1,
    type: "机会",
    title: "第一笔大订单超过了现有产能",
    narrative: "客户愿意预订，但交付周期、原料价格和验收标准都还模糊。营收机会第一次与现金流风险同时出现。",
    triggerTags: ["副业尝试", "经营", "客户", "企业"],
    guarded: ["先接一笔试订单", "缩小范围并收取定金，用一次完整交付验证毛利与流程。"],
    collaborative: ["联合供应商报价", "让关键供应商共同确认成本、交期和质量责任。"],
    bold: ["承接全部订单", "提前采购并扩大产能，争取占领客户预算。"],
  },
  {
    id: "business-inventory",
    pack: "business",
    stage: 2,
    type: "风险",
    title: "库存占用了利润，也占用了现金",
    narrative: "订单增长之后，仓库里出现畅销品缺货与慢销品积压。账面利润无法直接支付下个月工资。",
    triggerTags: ["经营", "库存", "现金流"],
    requiredAnyTags: ["人生包:business:1"],
    guarded: ["清理慢销库存", "用折扣换回现金，接受一部分毛利损失。"],
    collaborative: ["与供应商改成小批补货", "共享销售数据，协商更短账期与更小起订量。"],
    bold: ["押注旺季集中备货", "用更多流动性换取不断货和规模折扣。"],
  },
  {
    id: "business-partner",
    pack: "business",
    stage: 3,
    type: "关系",
    title: "合作伙伴要求重新分配股权",
    narrative: "对方认为客户和运营贡献没有被旧比例反映。友谊、控制权、历史投入与未来责任必须被放进同一张表。",
    triggerTags: ["企业", "关系", "股权", "合同"],
    requiredAnyTags: ["人生包:business:2"],
    guarded: ["先核算历史贡献", "把资金、客户、工时和承担的风险转成可讨论的证据。"],
    collaborative: ["设计动态股权方案", "让未来股权随里程碑归属，并补上离开与回购条款。"],
    bold: ["买下对方的份额", "用现金换取控制权，同时独自承担经营结果。"],
  },
  {
    id: "business-team",
    pack: "business",
    stage: 4,
    type: "职业",
    title: "明星员工的离开暴露了组织缺口",
    narrative: "关键客户、报价经验和交付诀窍集中在一个人身上。个人英雄主义正在变成企业的单点故障。",
    triggerTags: ["企业", "员工", "管理", "交付"],
    requiredAnyTags: ["人生包:business:3"],
    guarded: ["先完成知识交接", "整理客户记录、操作清单和权限，降低离职冲击。"],
    collaborative: ["建立团队分工与激励", "让客户、交付和复盘由多人共同负责。"],
    bold: ["高价引入职业经理人", "用更高固定成本换取流程化与更快扩张。"],
  },
  {
    id: "business-exit",
    pack: "business",
    stage: 5,
    type: "市场",
    title: "收购邀约迫使你定义企业价值",
    narrative: "买方愿意支付一笔可观现金，但要求你继续任职并承担业绩承诺。退出不是终点，而是现金、控制与时间的重新组合。",
    triggerTags: ["企业", "估值", "退出", "现金流"],
    requiredAnyTags: ["人生包:business:4"],
    guarded: ["拒绝出售并优化治理", "先降低对创始人的依赖，再等待更清晰的估值。"],
    collaborative: ["出售少数股权", "引入资源同时保留控制，并约定信息权和退出机制。"],
    bold: ["接受整体收购", "兑现企业价值，但承担业绩承诺与身份转换。"],
  },
  {
    id: "family-values",
    pack: "family",
    stage: 1,
    type: "家庭",
    title: "两个人第一次公开各自的消费观",
    narrative: "旅行、赡养、储蓄和个人自由在同一份预算里相遇。真正的分歧不是数字，而是每笔钱代表的安全感。",
    triggerTags: ["家庭", "透明沟通", "共同家庭", "关系"],
    guarded: ["先交换真实账单", "只核对收入、负债与固定责任，不急着合并账户。"],
    collaborative: ["建立共同目标账户", "保留个人空间，同时为共同目标设置自动投入。"],
    bold: ["全面合并家庭财务", "统一账户和决策规则，让所有风险与目标完全共享。"],
  },
  {
    id: "family-home",
    pack: "family",
    stage: 2,
    type: "家庭",
    title: "一套喜欢的房子超过了舒适预算",
    narrative: "通勤、学区、空间和稳定感都很诱人，但首付会抽干安全垫，月供也会固定未来很多年的选择。",
    triggerTags: ["家庭", "房产", "现金流", "机会成本"],
    requiredAnyTags: ["人生包:family:1"],
    guarded: ["继续租住并积累首付", "用流动性保留职业与城市选择权。"],
    collaborative: ["下调总价共同购房", "先设月供上限、产权比例与退出方案。"],
    bold: ["买下目标住房", "投入大部分现金并承担长期月供，换取当下稳定。"],
  },
  {
    id: "family-care",
    pack: "family",
    stage: 3,
    type: "家庭",
    title: "长辈的照护需求突然增加",
    narrative: "时间、医疗信息与费用同时压向家庭。谁请假、谁出钱、谁做决定，都不能只靠临时牺牲。",
    triggerTags: ["家庭", "照护", "健康", "保障"],
    requiredAnyTags: ["人生包:family:2"],
    guarded: ["先完成医疗与保障盘点", "确认诊疗路径、可报销费用和紧急联系人。"],
    collaborative: ["建立家庭照护轮班", "把时间、费用和决策职责分配给多位成员。"],
    bold: ["暂停工作承担主要照护", "用职业与收入机会换取更多陪伴和控制。"],
  },
  {
    id: "family-child",
    pack: "family",
    stage: 4,
    type: "家庭",
    title: "生育计划进入现实资源表",
    narrative: "意愿之外，还有照护时间、职业中断、住房、教育预期与支持网络。家庭要决定愿意承担怎样的长期责任。",
    triggerTags: ["家庭", "亲子", "照护", "职业"],
    requiredAnyTags: ["人生包:family:3"],
    guarded: ["先建立育儿缓冲", "补足现金、健康检查与照护备选，再决定时间表。"],
    collaborative: ["重排双方职业与照护", "明确休假、夜间照护和重返工作的共同方案。"],
    bold: ["立即进入新家庭阶段", "接受准备不完整，用更多当期投入换取时间窗口。"],
  },
  {
    id: "family-resilience",
    pack: "family",
    stage: 5,
    type: "风险",
    title: "一次收入中断检验了家庭系统",
    narrative: "房贷、照护和日常开支没有暂停。共同账户、保障、关系质量与可迁移能力开始共同发挥作用。",
    triggerTags: ["家庭", "应急金", "收入", "保障"],
    requiredAnyTags: ["人生包:family:4"],
    guarded: ["启动家庭生存预算", "暂停扩张性支出，优先守住住房、健康与必要照护。"],
    collaborative: ["共同重分配收入责任", "让有余力的一方增收，另一方承担更多家庭运营。"],
    bold: ["出售资产换取转型时间", "主动调整资产负债表，为新的职业路线争取窗口。"],
  },
  {
    id: "investment-policy",
    pack: "investment",
    stage: 1,
    type: "市场",
    title: "市场上涨让闲置现金显得格外刺眼",
    narrative: "身边的人都在分享收益截图。你缺少的可能不是热门标的，而是一套明确自己期限、目标与风险容量的投资政策。",
    triggerTags: ["投资", "持有资产", "市场", "现金流"],
    guarded: ["先写资产配置规则", "按目标期限确定现金、稳健与成长资产比例。"],
    collaborative: ["分批建立组合", "用固定节奏投入并记录每项资产的投资理由。"],
    bold: ["集中买入热门资产", "追求更高上涨弹性，同时接受集中度与估值风险。"],
  },
  {
    id: "investment-valuation",
    pack: "investment",
    stage: 2,
    type: "市场",
    title: "好资产的价格已经不再便宜",
    narrative: "基本面仍在增长，但乐观预期已经写进价格。买什么与付多少钱，开始成为两个不同问题。",
    triggerTags: ["投资", "估值", "资产", "机会成本"],
    requiredAnyTags: ["人生包:investment:1"],
    guarded: ["等待安全边际", "保留现金，设定可以解释的估值区间。"],
    collaborative: ["小仓位持续跟踪", "用有限持仓换取研究动力，并按事实修正判断。"],
    bold: ["为成长支付高溢价", "集中承担预期落空风险，争取长期复利。"],
  },
  {
    id: "investment-drawdown",
    pack: "investment",
    stage: 3,
    type: "风险",
    title: "组合在一个季度内明显回撤",
    narrative: "价格下跌、新闻恶化和生活支出同时出现。此刻的决策会暴露你的投资期限是否真的匹配资金用途。",
    triggerTags: ["投资", "衰退", "放缓", "风险承受力"],
    requiredAnyTags: ["人生包:investment:2"],
    guarded: ["先检查生活资金期限", "把未来两年的必需支出与波动资产彻底隔离。"],
    collaborative: ["按配置规则再平衡", "卖出相对高估资产，补回偏离目标的部分。"],
    bold: ["借款逆势加仓", "放大潜在收益，也放大期限错配和强制卖出风险。"],
  },
  {
    id: "investment-liquidity",
    pack: "investment",
    stage: 4,
    type: "风险",
    title: "急用钱时，最看好的资产卖不出去",
    narrative: "报价仍然存在，真实成交却需要巨大折价。流动性不再是报表上的词，而是能否按时履行家庭承诺。",
    triggerTags: ["投资", "流动性", "家庭", "负债"],
    requiredAnyTags: ["人生包:investment:3"],
    guarded: ["折价退出一部分", "承认流动性成本，先覆盖不可延期的责任。"],
    collaborative: ["协商延后资金需求", "用关系信用和清晰计划争取更合理的退出时间。"],
    bold: ["用短期负债等待反弹", "避免立即卖出，但承担利息与进一步下跌风险。"],
  },
  {
    id: "investment-cycle",
    pack: "investment",
    stage: 5,
    type: "市场",
    title: "穿越周期后，你要重写投资纪律",
    narrative: "收益、回撤和真实用钱时刻都留下了证据。复盘的目标不是解释过去，而是让下一次决策不再依赖情绪。",
    triggerTags: ["投资", "资产配置", "复盘", "长期主义"],
    requiredAnyTags: ["人生包:investment:4"],
    guarded: ["降低复杂度", "只保留理解、能持有且与目标期限匹配的资产。"],
    collaborative: ["建立年度再平衡机制", "按固定规则调整组合，而不是追逐最新叙事。"],
    bold: ["形成逆周期机会仓", "为极端错价预留资本，同时设定明确上限。"],
  },
  {
    id: "contract-loan",
    pack: "contract",
    stage: 1,
    type: "关系",
    title: "一位朋友请求你做借款担保",
    narrative: "对方承诺很快还款，并把拒绝理解为不信任。真正的问题是，你是否看清最坏情况下由谁承担债务。",
    triggerTags: ["关系", "帮助他人", "信用", "合同"],
    guarded: ["拒绝无限责任担保", "保持关系，但不签署无法承受的开放式责任。"],
    collaborative: ["帮助重做融资方案", "核对用途、还款来源和抵押，让风险回到借款本身。"],
    bold: ["基于信任直接担保", "用个人信用支持朋友，承担连带偿付风险。"],
  },
  {
    id: "contract-diligence",
    pack: "contract",
    stage: 2,
    type: "机会",
    title: "熟人带来一项“内部合作机会”",
    narrative: "回报诱人，资料却只在聊天记录里。关系来源不能替代资金流向、权利边界和交易对手调查。",
    triggerTags: ["关系", "合作", "尽调", "机会"],
    requiredAnyTags: ["人生包:contract:1"],
    guarded: ["先核验主体与资金用途", "查询登记、诉讼和收款账户，不因熟人跳过基本事实。"],
    collaborative: ["设计小额验证交易", "用可退出的里程碑测试对方履约能力。"],
    bold: ["抢先投入换取份额", "在信息不完整时换取更高回报承诺。"],
  },
  {
    id: "contract-scope",
    pack: "contract",
    stage: 3,
    type: "关系",
    title: "合作开始后，双方理解的责任不同",
    narrative: "交付、验收和客户归属都出现分歧。继续靠情面推进，会让每一次新增工作都变成新的争议。",
    triggerTags: ["合同", "合作", "交付", "谈判"],
    requiredAnyTags: ["人生包:contract:2"],
    guarded: ["暂停新增承诺", "整理已有证据，先恢复清晰边界。"],
    collaborative: ["补签变更与验收条款", "把分歧转成可执行的责任、价格和时间表。"],
    bold: ["继续口头推进", "用速度维持表面关系，承担回款与责任扩张风险。"],
  },
  {
    id: "contract-compliance",
    pack: "contract",
    stage: 4,
    type: "风险",
    title: "一笔回款触发了合规审查",
    narrative: "平台要求说明合同、发票与资金来源。业务真实不等于证据完整，流程缺口正在冻结正常现金流。",
    triggerTags: ["合同", "合规", "现金流", "企业"],
    requiredAnyTags: ["人生包:contract:3"],
    guarded: ["停止相关交易并补证据", "先恢复资金链条与业务事实的一致性。"],
    collaborative: ["引入专业复核", "让会计与法律顾问共同修复合同、票据和流程。"],
    bold: ["换通道继续收款", "绕开当前限制，承担更大的账户与合规风险。"],
  },
  {
    id: "contract-exit",
    pack: "contract",
    stage: 5,
    type: "关系",
    title: "长期合作走到退出谈判",
    narrative: "客户、数据、知识产权和未结款项都需要归属。成熟的退出机制决定这段关系能否留下信用，而不是只留下冲突。",
    triggerTags: ["合同", "退出", "信用", "关系复利"],
    requiredAnyTags: ["人生包:contract:4"],
    guarded: ["按现有条款有序退出", "完成交接、结算与权限回收，避免新增争议。"],
    collaborative: ["重谈双赢退出方案", "用过渡服务换取及时回款和公开推荐。"],
    bold: ["立即终止并追责", "优先维护权利，接受时间、费用与关系损失。"],
  },
  {
    id: "consumer-installment",
    pack: "consumer",
    stage: 1,
    type: "风险",
    title: "零首付让一次升级消费看起来毫无压力",
    narrative: "每月金额很小，但手续费、自动续费和多笔分期会共同占用未来现金流。便宜的是当下感觉，不一定是总成本。",
    triggerTags: ["消费", "负债", "现金缓冲不足", "现金流"],
    guarded: ["按总成本重新比较", "把利息、手续费和失去的流动性全部写入价格。"],
    collaborative: ["设置消费冷静期", "和家庭共同设定延迟购买与预算上限。"],
    bold: ["接受分期立即升级", "提前获得体验，用未来固定支出承担代价。"],
  },
  {
    id: "consumer-subscription",
    pack: "consumer",
    stage: 2,
    type: "风险",
    title: "十几个自动续费正在安静地增长",
    narrative: "每项服务都不贵，但低使用率订阅与会员折扣诱导了更多消费。小额固定承诺已经变成生活的隐形税。",
    triggerTags: ["消费", "固定支出", "家庭", "机会成本"],
    requiredAnyTags: ["人生包:consumer:1"],
    guarded: ["逐项取消低使用订阅", "按最近九十天真实使用记录决定保留什么。"],
    collaborative: ["建立家庭共享清单", "去掉重复服务并设置续费前共同提醒。"],
    bold: ["购买长期套餐锁定折扣", "一次支付更多现金，赌未来持续使用。"],
  },
  {
    id: "consumer-status",
    pack: "consumer",
    stage: 3,
    type: "关系",
    title: "圈层活动把消费包装成职业投资",
    narrative: "昂贵着装、会籍和聚会被解释为进入机会网络的门票。它可能产生关系，也可能只是把身份焦虑变成账单。",
    triggerTags: ["消费", "关系", "职业", "信用"],
    requiredAnyTags: ["人生包:consumer:2"],
    guarded: ["只参加目标明确的活动", "预先定义想认识的人和可以提供的价值。"],
    collaborative: ["用贡献替代昂贵消费", "通过组织、分享或志愿工作进入真实关系。"],
    bold: ["用高消费塑造新身份", "迅速进入圈层场景，承担持续支出与攀比压力。"],
  },
  {
    id: "consumer-credit",
    pack: "consumer",
    stage: 4,
    type: "风险",
    title: "多笔小额负债开始互相挤压",
    narrative: "还款日分散、利率不同，最低还款掩盖了本金几乎没有下降。现金流已经失去容错空间。",
    triggerTags: ["负债管理", "主动降债", "现金流", "压力"],
    requiredAnyTags: ["人生包:consumer:3"],
    guarded: ["停止新增并滚雪球还款", "按余额或利率排序，把释放的额度继续用于还债。"],
    collaborative: ["协商整合还款计划", "降低利率并固定期限，同时关闭循环额度。"],
    bold: ["借新还旧维持消费", "缓解当前账单，但继续放大长期负担。"],
  },
  {
    id: "consumer-reset",
    pack: "consumer",
    stage: 5,
    type: "机会",
    title: "消费重置释放出一笔稳定月度现金流",
    narrative: "债务和隐形支出下降后，新的结余需要一个去向。否则短暂克制很快会被生活方式膨胀重新吞没。",
    triggerTags: ["消费", "现金流", "投资", "家庭"],
    requiredAnyTags: ["人生包:consumer:4"],
    guarded: ["自动补足应急金", "先把结余转成能够抵御突发事件的选择权。"],
    collaborative: ["分配给共同目标", "让家庭为长期目标和当下体验共同设定比例。"],
    bold: ["投入高成长资产", "把全部新增结余用于追求长期回报，接受波动。"],
  },
  {
    id: "platform-audience",
    pack: "platform",
    stage: 1,
    type: "机会",
    title: "一条内容意外带来第一批真实关注",
    narrative: "流量突然增长，但受众为什么留下还不清楚。把偶然曝光变成可重复价值，需要内容、产品与交付共同验证。",
    triggerTags: ["副业尝试", "自由机会", "平台", "收入多元"],
    guarded: ["访谈十位真实受众", "先找出他们的问题和愿意持续关注的原因。"],
    collaborative: ["共创一个小型产品", "邀请早期用户参与测试并用反馈迭代。"],
    bold: ["立即购买流量扩张", "在定位尚未稳定时放大曝光与获客成本。"],
  },
  {
    id: "platform-pricing",
    pack: "platform",
    stage: 2,
    type: "职业",
    title: "第一批客户要求“粉丝友情价”",
    narrative: "低价有助于成交，却可能让交付时间失去回报。定价开始筛选客户，也开始定义这份工作的可持续性。",
    triggerTags: ["副业尝试", "客户", "定价", "交付"],
    requiredAnyTags: ["人生包:platform:1"],
    guarded: ["提供范围受限的入门版", "降低价格的同时明确减少交付与支持。"],
    collaborative: ["按价值共同定义报价", "围绕客户结果、验收和付款节点形成方案。"],
    bold: ["低价换取规模与案例", "牺牲短期利润，押注口碑与后续转化。"],
  },
  {
    id: "platform-delivery",
    pack: "platform",
    stage: 3,
    type: "风险",
    title: "主业、内容和客户交付同时到期",
    narrative: "收入来源增加了，时间却没有。延迟、健康透支和质量下降会把机会转化成信用损失。",
    triggerTags: ["副业尝试", "交付", "健康", "机会成本"],
    requiredAnyTags: ["人生包:platform:2"],
    guarded: ["暂停接单清理交付", "用短期增长换回质量、睡眠与客户信任。"],
    collaborative: ["引入伙伴分担流程", "标准化重复环节，并明确客户与收入分配。"],
    bold: ["继续满负荷扩张", "赌自己能穿过高峰，承担健康与违约风险。"],
  },
  {
    id: "platform-account",
    pack: "platform",
    stage: 4,
    type: "风险",
    title: "平台风控冻结了主要账号",
    narrative: "流量、客户联系方式和待结算收入集中在同一平台。规则变化一夜之间变成经营中断。",
    triggerTags: ["平台", "账户", "现金流", "风险"],
    requiredAnyTags: ["人生包:platform:3"],
    guarded: ["申诉并保存全部证据", "停止高风险操作，按规则恢复账户与结算。"],
    collaborative: ["迁移客户到自有渠道", "用邮件、社群和合同建立可携带的客户关系。"],
    bold: ["用新账号快速重启", "抢回流量窗口，承担关联处罚与再次冻结风险。"],
  },
  {
    id: "platform-portfolio",
    pack: "platform",
    stage: 5,
    type: "职业",
    title: "平台生意需要变成可携带的职业资产",
    narrative: "受众、案例、产品与客户数据已经积累。下一步不只是继续发内容，而是降低对单一平台和个人工时的依赖。",
    triggerTags: ["平台", "作品", "客户", "收入多元"],
    requiredAnyTags: ["人生包:platform:4"],
    guarded: ["沉淀作品与客户档案", "建立可验证案例、自有联系方式和标准服务。"],
    collaborative: ["形成产品与伙伴组合", "让内容、社群和交付由不同角色共同运行。"],
    bold: ["全职经营个人品牌", "退出主业并集中资源，追求更大的长期复利。"],
  },
];

const PROFILES: Record<LifeStoryPack, Record<Strategy, StrategyProfile>> = {
  business: {
    guarded: { risk: "低", cost: 2_000, timeCost: 1, baseProbability: 0.82, effects: { cash: -2_000, energy: -2 }, successEffects: { credit: 2, stress: -1 }, failureEffects: { stress: 2 }, knowledge: ["现金流", "小步验证", "治理"] },
    collaborative: { risk: "中", cost: 5_000, timeCost: 2, baseProbability: 0.67, effects: { cash: -5_000, energy: -4 }, successEffects: { monthlyIncome: 520, relationship: 4, credit: 2 }, failureEffects: { relationship: -2, stress: 4 }, knowledge: ["合同", "关系复利", "企业治理"] },
    bold: { risk: "高", cost: 12_000, timeCost: 3, baseProbability: 0.44, effects: { cash: -12_000, energy: -7, stress: 3 }, successEffects: { cash: 24_000, monthlyIncome: 1_000, happiness: 3 }, failureEffects: { cash: -6_000, stress: 8, credit: -3 }, knowledge: ["经营杠杆", "风险承受力", "退出机制"] },
  },
  family: {
    guarded: { risk: "低", cost: 1_000, timeCost: 1, baseProbability: 0.84, effects: { cash: -1_000, energy: -2 }, successEffects: { relationship: 3, stress: -3 }, failureEffects: { relationship: -1, stress: 2 }, knowledge: ["家庭责任", "风险缓冲", "共同财务"] },
    collaborative: { risk: "中", cost: 4_000, timeCost: 2, baseProbability: 0.7, effects: { cash: -4_000, energy: -4 }, successEffects: { relationship: 7, happiness: 3, stress: -3 }, failureEffects: { relationship: -3, stress: 4 }, knowledge: ["透明沟通", "照护分工", "机会成本"] },
    bold: { risk: "高", cost: 14_000, timeCost: 3, baseProbability: 0.5, effects: { cash: -14_000, energy: -7, stress: 4 }, successEffects: { relationship: 5, happiness: 7, fixedExpense: 260 }, failureEffects: { relationship: -5, stress: 9, happiness: -3 }, knowledge: ["长期承诺", "家庭韧性", "期限匹配"] },
  },
  investment: {
    guarded: { risk: "低", cost: 1_500, timeCost: 1, baseProbability: 0.83, effects: { cash: -1_500, energy: -1 }, successEffects: { passiveIncome: 80, stress: -2 }, failureEffects: { stress: 2 }, knowledge: ["资产配置", "安全边际", "流动性"] },
    collaborative: { risk: "中", cost: 6_000, timeCost: 2, baseProbability: 0.64, effects: { cash: -6_000, energy: -2 }, successEffects: { cash: 3_000, passiveIncome: 220, credit: 1 }, failureEffects: { cash: -2_000, stress: 4 }, knowledge: ["再平衡", "估值", "能力圈"] },
    bold: { risk: "极高", cost: 16_000, timeCost: 2, baseProbability: 0.38, effects: { cash: -16_000, stress: 3 }, successEffects: { cash: 38_000, passiveIncome: 420, happiness: 4 }, failureEffects: { cash: -12_000, debt: 6_000, stress: 10 }, knowledge: ["杠杆", "期限错配", "周期"] },
  },
  contract: {
    guarded: { risk: "低", cost: 800, timeCost: 1, baseProbability: 0.86, effects: { cash: -800, energy: -1 }, successEffects: { credit: 3, stress: -2 }, failureEffects: { relationship: -1, stress: 2 }, knowledge: ["尽职调查", "证据链", "合规"] },
    collaborative: { risk: "中", cost: 3_000, timeCost: 2, baseProbability: 0.71, effects: { cash: -3_000, energy: -3 }, successEffects: { relationship: 5, credit: 4, monthlyIncome: 180 }, failureEffects: { relationship: -3, stress: 4 }, knowledge: ["合同", "谈判", "退出机制"] },
    bold: { risk: "高", cost: 8_000, timeCost: 2, baseProbability: 0.42, effects: { cash: -8_000, stress: 3 }, successEffects: { cash: 16_000, relationship: 4, credit: 2 }, failureEffects: { debt: 8_000, relationship: -8, credit: -6, stress: 9 }, knowledge: ["连带责任", "交易对手", "信用"] },
  },
  consumer: {
    guarded: { risk: "低", cost: 0, timeCost: 1, baseProbability: 0.88, effects: { energy: -1 }, successEffects: { cash: 3_000, fixedExpense: -120, stress: -2 }, failureEffects: { happiness: -1 }, knowledge: ["总拥有成本", "延迟满足", "现金流"] },
    collaborative: { risk: "中", cost: 600, timeCost: 1, baseProbability: 0.75, effects: { cash: -600, energy: -1 }, successEffects: { cash: 4_000, fixedExpense: -180, relationship: 3 }, failureEffects: { relationship: -2, stress: 2 }, knowledge: ["家庭预算", "消费冷静期", "机会成本"] },
    bold: { risk: "高", cost: 9_000, timeCost: 1, baseProbability: 0.48, effects: { cash: -9_000, fixedExpense: 240 }, successEffects: { happiness: 5, relationship: 2 }, failureEffects: { debt: 5_000, stress: 7, happiness: -3 }, knowledge: ["生活方式膨胀", "消费信贷", "身份消费"] },
  },
  platform: {
    guarded: { risk: "低", cost: 1_200, timeCost: 1, baseProbability: 0.82, effects: { cash: -1_200, energy: -3 }, successEffects: { monthlyIncome: 180, credit: 2 }, failureEffects: { stress: 2 }, knowledge: ["客户验证", "内容复利", "定价"] },
    collaborative: { risk: "中", cost: 3_500, timeCost: 2, baseProbability: 0.66, effects: { cash: -3_500, energy: -4 }, successEffects: { monthlyIncome: 480, relationship: 4, credit: 3 }, failureEffects: { relationship: -2, stress: 5 }, knowledge: ["应收账款", "合作边界", "渠道分散"] },
    bold: { risk: "高", cost: 9_000, timeCost: 3, baseProbability: 0.43, effects: { cash: -9_000, energy: -8, stress: 4 }, successEffects: { cash: 14_000, monthlyIncome: 900, happiness: 4 }, failureEffects: { cash: -5_000, health: -4, stress: 9 }, knowledge: ["平台风险", "个人品牌", "经营杠杆"] },
  },
};

function makeChoice(spec: LifeStorySpec, strategy: Strategy): EventChoice {
  const profile = PROFILES[spec.pack][strategy];
  const copy = spec[strategy];
  return {
    id: `${spec.id}-${strategy}`,
    label: copy[0],
    description: copy[1],
    cost: profile.cost,
    timeCost: profile.timeCost,
    risk: profile.risk,
    baseProbability: profile.baseProbability,
    effects: { ...profile.effects },
    successEffects: { ...profile.successEffects },
    failureEffects: { ...profile.failureEffects },
    knowledgeTags: [...profile.knowledge],
    memoryTags: [
      `人生包:${spec.pack}:${spec.stage}`,
      `人生包:事件:${spec.id}`,
      `人生策略:${strategy}`,
    ],
  };
}

export const LIFE_STORY_EVENTS: EventDefinition[] = SPECS.map((spec) => ({
  id: spec.id,
  type: spec.type,
  title: spec.title,
  narrative: spec.narrative,
  minTurn: spec.stage,
  requiredAnyTags: spec.requiredAnyTags,
  blockedTags: [`人生包:事件:${spec.id}`],
  triggerTags: spec.triggerTags,
  storyPackId: `life-${spec.pack}`,
  storyStage: spec.stage,
  weight: spec.stage === 1 ? 1.2 : 1.85,
  choices: [makeChoice(spec, "guarded"), makeChoice(spec, "collaborative"), makeChoice(spec, "bold")],
}));
